fix #148 (Change label in Request housing form)
code4romania/war-support-un-acoperis pull request #156
Opened 2022-03-04 17:36 UTC by danut3101

### Requirements for making a pull request

Thank you for contributing to our project! 

Please fill out the template below to help the project maintainers review it as fast as possible and include your contribution to the project.

### What does it fix?

Closes 

Please mention the main changes this PR brings.

### How has it been tested?

Please describe the tests that you ran to verify your changes.

2022-03-04 17:43 UTC, danut3101 commented
Este, de fapt pentru #147

2022-03-05 02:02 UTC, gheorghelupu17 commented on resources/views/host/home.blade.php
> +        'text' => $termsAndConditionsForHosts
Lasă butonul sa ducă aici te rog http://un-acoperis.heroesof.tech/host/accommodation/add

2022-03-05 02:04 UTC, gheorghelupu17 submitted a review, later dismissed

2022-03-05 02:04 UTC, gheorghelupu17 commented on resources/views/refugee/home.blade.php
> +        'text' => $termsAndConditionsForRefugees
Idem ca mai sus lasă butonul sa ducă la formular te rog

2022-03-05 05:20 UTC, danut3101 commented on resources/views/refugee/home.blade.php
> +        'text' => $termsAndConditionsForRefugees
LA fel ca mai sus...

2022-03-05 09:20 UTC, andreiio requested changes
Changes unrelated to the issue shouldn't be part of this PR

2022-03-05 09:20 UTC, andreiio commented on app/Http/Controllers/Host/ProfileController.php
> +use A17\Twill\Repositories\SettingRepository;
```suggestion
```

2022-03-05 09:20 UTC, andreiio commented on app/Http/Controllers/Host/ProfileController.php
> +    public function home(SettingRepository $settingRepository): View
```suggestion
    public function home(): View
```

2022-03-05 09:20 UTC, andreiio commented on app/Http/Controllers/Host/ProfileController.php
> +            ->with('termsAndConditionsForHosts', $settingRepository->byKey('terms_and_conditions_for_hosts') ?? '');
```suggestion
        return view('host.home');
```

2022-03-05 09:20 UTC, andreiio commented on app/Http/Controllers/Refugee/ProfileController.php
> +use A17\Twill\Repositories\SettingRepository;
```suggestion
```

2022-03-05 09:20 UTC, andreiio commented on app/Http/Controllers/Refugee/ProfileController.php
> +    public function home(SettingRepository $settingRepository): View
```suggestion
    public function home(): View
```

2022-03-05 09:20 UTC, andreiio commented on app/Http/Controllers/Refugee/ProfileController.php
> +            ->with('termsAndConditionsForRefugees', $settingRepository->byKey('terms_and_conditions_for_refugees') ?? '');
```suggestion
        return view('refugee.home');
```

2022-03-05 09:20 UTC, andreiio commented on resources/views/host/home.blade.php
> +        'text' => $termsAndConditionsForHosts
```suggestion
        'text' => __('host.general.terms.text'),
        'buttonText' => __('View Terms And Conditions'),
        'buttonUrl' => route('terms-host')
```

2022-03-05 09:20 UTC, andreiio commented on resources/views/refugee/home.blade.php
> +        'text' => $termsAndConditionsForRefugees
```suggestion
        'text' => __('refugee.general.terms.text'),
        'buttonText' => __('View Terms And Conditions'),
        'buttonUrl' => route('terms-refugee')
```

2022-03-05 09:22 UTC, andreiio commented on resources/lang/ro.json
> +    "Please give us more details about the case you are bringing to our attention": "Te rugăm să ne oferi mai multe detalii despre situația ta ca sa te ajutăm cât mai repede.",
```suggestion
    "Please give us more details about the case you are bringing to our attention": "Te rugăm să ne oferi mai multe detalii despre situația ta ca să te ajutăm cât mai repede.",
```

2022-03-05 09:22 UTC, andreiio approved these changes

2022-03-05 09:38 UTC, andreiio commented on app/Http/Controllers/Refugee/ProfileController.php
>          return view('refugee.home');
```suggestion

        return view('refugee.home');
```

2022-03-05 12:59 UTC, merged