WIP accommodation rating system
code4romania/war-support-un-acoperis pull request #165
Opened 2022-03-05 01:13 UTC by sherbastian

### Requirements for making a pull request

Thank you for contributing to our project! 

Please fill out the template below to help the project maintainers review it as fast as possible and include your contribution to the project.

### What does it fix?

Closes https://github.com/code4romania/war-support-un-acoperis/issues/151

Please mention the main changes this PR brings.

### How has it been tested?

Please describe the tests that you ran to verify your changes.

2022-03-06 00:34 UTC, sherbastian commented
should be ok for review

2022-03-07 21:57 UTC, beniamin commented
Din ce inteleg, intr-un loc de cazare pot sta mai multi refugiati. Asta inseamna ca in pagina spatiului de cazare, un host ar trebui sa poata alege carui refugiat sa ii lase review-ul.

2022-03-07 22:18 UTC, beniamin commented
sistemul de rating ar trebui sa fie in ambele directii: atat refugiatul sa poata da review unei cazari cat si gazda sa poata da review unui refugiat.

Propun ca in acest PR sa rezolvam doar parte de review de la un refugiat pentru o cazare, iar review-ul in cealalta directie sa il facem intr-un PR separat.

2022-03-07 22:21 UTC, beniamin commented
Box-ul de review pentru o cazare apare atat pentru refugiat cat si pentru gazda, dar bat ambele in acelasi endpoint de review al refugiatului pentru cazare. Ar trebui ca box-ul sa nu apara host-ului.

2022-03-07 22:30 UTC, sherbastian commented
> Box-ul de review pentru o cazare apare atat pentru refugiat cat si pentru gazda, dar bat ambele in acelasi endpoint de review al refugiatului pentru cazare. Ar trebui ca box-ul sa nu apara host-ului.

uu nice catch, fixez acum

2022-03-07 22:36 UTC, beniamin commented
Poti adauga ceva erori mai user friendly pentru validarile de pe campuriel de review? ai aici cateva detalii: https://laravel.com/docs/7.x/validation#customizing-the-error-messages

2022-03-07 23:25 UTC, sherbastian commented
> Pare ca rating-ul nu se seteaza corect. Oricat stelute as selecta, valoarea trimisa in backend este tot 0.
> 
> Poti adauga ceva erori mai user friendly pentru validarile de pe campuriel de review? ai aici cateva detalii: https://laravel.com/docs/7.x/validation#customizing-the-error-messages

Done :+1:

2022-03-09 08:08 UTC, beniamin commented
am deschis un PR in branch-ul tau cu niste modificari.

2022-03-09 19:28 UTC, beniamin approved these changes

2022-03-17 19:30 UTC, andreiio requested changes
We're mostly there. Mai rămân de rezolvat înainte să facem merge:

1. câteva todo comments prin cod;
2. o sugestie de extra checks de la @beniamin;
3. the merge conflict

2022-03-17 19:30 UTC, andreiio commented on resources/views/common/accommodation/view-accommodation.blade.php
> +            @if ($accommodation->reviewedByUser(auth()->user()))
```suggestion
            @if ($accommodation->isReviewedBy(auth()->user()))
```

2025-08-13 12:04 UTC, closed without merging