Docker apache
code4romania/war-support-un-acoperis pull request #216
Opened 2022-03-10 10:22 UTC by Utwo

### What does it fix?

Use one container for the app (php-apache) instead of two (php-fpm + nginx) to be easier to deploy on knative. 

### How has it been tested?

This version of the image was already deployed on stage server.

2022-03-10 10:58 UTC, beniamin commented on .docker/php/Dockerfile
> -RUN set -ex \
din ce am inteles aplicatia are nevoie de imagick, sigur e ok sa il stergi?

2022-03-10 11:00 UTC, Utwo commented on .docker/php/Dockerfile
> -RUN set -ex \
Hmmm, good catch. Verific cu @andreiio si daca este nevoie, il pun inapoi.

2022-03-10 11:08 UTC, beniamin reviewed
Pt ca ai modificat comanda continerului de nodejs, va trebui sa modifici si in Makefile si in loc de docker-compose exec sa folosesti docker-compose run.

2022-03-10 11:08 UTC, beniamin commented on README.md
> +-   `docker-compose exec nodejs sh -c 'npm run watch'` - start npm hot-reloading for js files
aici trebuie corectat. Containerul de nodejs nu mai ruleaza tot timpul ca sa posti face exec pe el, si va trebui sa il pornesti de fiecare data.

2022-03-10 11:17 UTC, beniamin commented on .docker/php/Dockerfile
> -COPY .docker/php/zz-custom.ini /usr/local/etc/php/conf.d/zz-custom.ini
apache are opcache activat by default?

2022-03-10 11:23 UTC, Utwo commented on README.md
> +-   `docker-compose exec nodejs sh -c 'npm run watch'` - start npm hot-reloading for js files
Credeam ca `npm run dev` ii pentru a rula local in watch mode. Am sa schimb inapoi in `npm run watch`. Mersi!

2022-03-10 11:31 UTC, beniamin commented on README.md
> +-   `docker-compose exec nodejs sh -c 'npm run watch'` - start npm hot-reloading for js files
`npm run watch` e destul de intensive, si nu e tot timpul nevoie de el. In cele mai multe situatii nu ai nevoie sa tot rebuild-uiesti js-urile.

Setup-ul curent ruleaza `npm run dev`ca sa compileze js-urile initial. Daca dev-ul are nevoie de hot-reloading trebuie sa porneasca singur watch-ul.

E ok si cum ai facut tu, acum dupa ce am testat am vazut ca dupa ce termina comanda se inchide containerul si toata lumea e fericita.

2022-03-10 11:52 UTC, Utwo commented on README.md
> +-   `docker-compose exec nodejs sh -c 'npm run watch'` - start npm hot-reloading for js files
Bun, am pus `npm run dev` in compose si am schimbat in readme si in Makefile. In Makefile install nu ar trebui sa mai avem nevoie de `npm run dev` inca o data pentru ca se ruleaza deja in compose.

2022-03-10 11:53 UTC, Utwo commented on .docker/php/Dockerfile
> -COPY .docker/php/zz-custom.ini /usr/local/etc/php/conf.d/zz-custom.ini
Eu stiam ca dupa php 5.5 vine automat. Acuma ca nu mai exista php-apache-alpine m-am asteptat sa fie. Far verific acuma.

2022-03-10 11:58 UTC, beniamin commented on README.md
> +-   `docker-compose exec nodejs sh -c 'npm run watch'` - start npm hot-reloading for js files
da e ok.

2022-03-10 13:13 UTC, Utwo commented on .docker/php/Dockerfile
> -COPY .docker/php/zz-custom.ini /usr/local/etc/php/conf.d/zz-custom.ini
Da, este enabled. Am mai facut un fix sa pun PHP_OPCACHE_VALIDATE_TIMESTAMPS pe 0 daca este in prod

2022-03-10 13:14 UTC, Utwo commented on README.md
> +-   `docker-compose exec nodejs sh -c 'npm run watch'` - start npm hot-reloading for js files
Nu-mi arata link-ul exact... :(

2022-03-10 13:15 UTC, Utwo commented on .docker/php/Dockerfile
> -RUN set -ex \
Am pus si imagick inapooi

2022-03-10 15:25 UTC, beniamin commented on .docker/php/Dockerfile
> +    apt-get install -y --no-install-recommends libzip-dev libpng-dev libicu-dev libmagickwand-dev zlib1g-dev && \
poti adauga si zip in lista de pachete de instalat? Se plange composerul la install:
"As there is no 'unzip' nor '7z' command installed zip files are being unpacked using the PHP zip extension."

2022-03-10 17:27 UTC, andreiio requested changes

2022-03-10 17:27 UTC, andreiio commented on .docker/php/zz-custom.ini
> -post_max_size = 128M
we need these pentru file upload

2022-03-10 18:17 UTC, andreiio commented on docker-compose.yml
> +        npm run dev
```suggestion
        npm run prod
```

2022-03-10 18:22 UTC, andreiio commented on docker-compose.yml
> +        npm run prod
```suggestion
        npm run dev
```

2022-03-10 20:13 UTC, beniamin commented on README.md
> +-   `docker-compose exec nodejs sh -c 'npm run watch'` - start npm hot-reloading for js files
fixed.

2022-03-10 20:17 UTC, beniamin commented on docker-compose.yml
> +      PHP_OPCACHE_VALIDATE_TIMESTAMPS: 1
nu cred ca are sens sa tii opcache pornit pe dev si sa tot faci reset de cache la fiecare modificare. s-ar putea chiar sa intampini probleme.
as inlocui config-ul asta cu un config de genul PHP_OPCACHE_ENABLED si pe dev sa il tin dezactivat.

2022-03-11 07:54 UTC, beniamin approved these changes

2022-03-11 08:00 UTC, beniamin commented on docker-compose.yml
> -      target: dev_stage
nu cred ca are rost pe dev sa build-uiesti toate stage-urile, incusiv sa build-uiesti nodejs din moment ce nu vor fi folosite si oricum va fi nevoie sa faci din nou composer install/npm ci && npm run dev

2022-03-11 11:34 UTC, andreiio approved these changes

2022-03-11 11:51 UTC, beniamin approved these changes

2022-03-11 13:05 UTC, merged