add host unit is free agreement checkbox
code4romania/war-support-un-acoperis pull request #241
Opened 2022-03-12 17:05 UTC by beniamin

### Requirements for making a pull request

Thank you for contributing to our project! 

Please fill out the template below to help the project maintainers review it as fast as possible and include your contribution to the project.

### What does it fix?

Adds a new agreement checkbox in add accommodation form, in order for host user to consent that the hosting unit is completely free.

### How has it been tested?

2022-03-12 17:07 UTC, beniamin commented on app/Http/Controllers/StaticPagesController.php
> -        $helpRequests = HelpRequest::all()->count();
am facut putin curatenie, nu pare sa fie afisate pe undeva prin front astea, asa ca le-am scos pentru ca se faceau niste query-uri degeaba.

2022-03-12 17:07 UTC, beniamin commented on app/Accommodation.php
> -    public function scopeIsFree(Builder $query): Builder
nu mai este folosita din cauza de cleanup pe homepage.

2022-03-12 17:07 UTC, beniamin commented on resources/views/frontend/home.blade.php
> -    {{-- <div class="container py-5">
niste curatenie pe homepage.

2022-03-12 17:40 UTC, andreiio commented on resources/views/frontend/home.blade.php
> -    {{-- <div class="container py-5">
leave this in, a fost removed doar cu titlu temporar

2022-03-12 18:33 UTC, gheorghelupu17 requested changes

2022-03-12 18:33 UTC, gheorghelupu17 commented on docker-compose.yml
> +      - ./:/var/www:delegated
Pls roll back here

2022-03-12 18:37 UTC, beniamin commented on docker-compose.yml
> +      - ./:/var/www:delegated
e aceeasi modificare care s-a dus si pe main mai devreme putin: https://github.com/code4romania/war-support-un-acoperis/commit/faf5c96fc00e3090ad3819ecfd6cc790ccfe109a#diff-e45e45baeda1c1e73482975a664062aa56f20c03dd9d64a827aba57775bed0d3R14

2022-03-12 22:10 UTC, beniamin commented on resources/views/frontend/home.blade.php
> -    {{-- <div class="container py-5">
done

2022-03-13 19:10 UTC, gheorghelupu17 approved these changes

2022-03-13 19:10 UTC, merged