Lng
code4romania/war-support-un-acoperis pull request #33
Opened 2022-02-26 20:44 UTC by lzomedia

### Requirements for making a pull request

Thank you for contributing to our project! 

Please fill out the template below to help the project maintainers review it as fast as possible and include your contribution to the project.

### What does it fix?

Closes 

Please mention the main changes this PR brings.

### How has it been tested?

Please describe the tests that you ran to verify your changes.

2022-02-26 21:31 UTC, andreiio requested changes

2022-02-26 21:31 UTC, andreiio commented on .env.example
> +APP_LANG="en"
nu e nevoie să setăm limba din env

```suggestion
```

2022-02-26 21:31 UTC, andreiio commented on app/Http/Controllers/StaticPagesController.php
> +     * @todo add return type
unrelated to task, please remove

```suggestion
```

2022-02-26 21:31 UTC, andreiio commented on app/Http/Middleware/SecurityHeaders.php
> +        $allowedHosts = ['helpforhealth.loc', 'impreunapentrusanatate.ro', 'dev.impreunapentrusanatate.ro'];
unrelated to task, please revert

```suggestion
        $allowedHosts = ['helpforhealth.local', 'impreunapentrusanatate.ro', 'dev.impreunapentrusanatate.ro'];
```

2022-02-26 21:31 UTC, andreiio commented on config/app.php
> +    'locale' => env('APP_LANG', 'en'),
nu e nevoie să setăm limba din env

```suggestion
    'locale' => 'ro',
```

2022-02-26 21:31 UTC, andreiio commented on app/Http/Middleware/SetLanguage.php
>          if (!empty($routeLocaleValue) && in_array($routeLocaleValue, self::ACCEPTED_LANGUAGES)) {
folosim lista de coduri din config

```suggestion
        if (!empty($routeLocaleValue) && in_array($routeLocaleValue, config('translatable.locales'))) {
```

2022-02-26 21:31 UTC, andreiio commented on app/Http/Middleware/SetLanguage.php
> +    const ACCEPTED_LANGUAGES = ['ro', 'en','ua', 'ru'];
știu că asta făcea deja parte din cod, dar putem trage lista de coduri de limbă din config, în loc să o duplicăm și aici.

```suggestion
```

Poate fi șters după ce e făcută următoarea modificare în [`app/Http/Controllers/AjaxController.php:312`](https://github.com/code4romania/war-support-un-acoperis/blob/development/app/Http/Controllers/AjaxController.php#L312):

din
```php
        $locale = in_array($path[0] ?? '', SetLanguage::ACCEPTED_LANGUAGES) ?
            $path[0] :
            null;
```

în
```php
        $locale = in_array($path[0] ?? '', config('translatable.locales')) ?
            $path[0] :
            null;
```

2022-02-26 21:45 UTC, lzomedia commented
andrei exista la englezi o vorba :) 
you are taking the piss :)

2022-02-26 22:28 UTC, lzomedia commented on .env.example
> +APP_LANG="en"
sa pun ro ?

2022-02-26 22:28 UTC, lzomedia commented on app/Http/Controllers/StaticPagesController.php
> +     * @todo add return type
this actualy needs ref

2022-02-26 22:31 UTC, lzomedia commented on app/Http/Middleware/SecurityHeaders.php
> +        $allowedHosts = ['helpforhealth.loc', 'impreunapentrusanatate.ro', 'dev.impreunapentrusanatate.ro'];
my bad i used a diff . name
one  my ask qhy ask why we so that check when that check should be in CFG

2022-02-26 22:32 UTC, lzomedia commented on config/app.php
> +    'locale' => env('APP_LANG', 'en'),
eu zic ca da , nu stiu sa se voteze

2022-02-26 22:35 UTC, lzomedia commented on config/translatable.php
> +        'ua',
> codul pentru limba ucraineană e `UK`. codul pentru Ucraina e `UA`. ([source](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes#UK))

eu sunt moldovian da la ukraine pe d2 nu e asa e ua stiu  am avurt aceasi problema si am luat 4 la mate :)

2022-02-26 22:48 UTC, andreiio commented on .env.example
> +APP_LANG="en"
nu, nu e nevoie să existe, că limba activă se schimbă în funcție de request

2022-02-26 22:48 UTC, andreiio commented on app/Http/Controllers/StaticPagesController.php
> +     * @todo add return type
dacă e necesar, poate exista într-un PR separat

2022-02-26 22:49 UTC, andreiio commented on app/Http/Middleware/SecurityHeaders.php
> +        $allowedHosts = ['helpforhealth.loc', 'impreunapentrusanatate.ro', 'dev.impreunapentrusanatate.ro'];
nu zic că trebuie să existe, ci doar că nu e legat de task-ul curent de localization

2022-02-27 08:49 UTC, andreiio commented
Closing this in favor of #47 .

2022-02-27 08:49 UTC, closed without merging

2022-02-27 11:13 UTC, lzomedia commented
vreausi eu o explicatie  in privat